name: core-streams-update

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pulumi:
    uses: proxima-one/github-workflows/.github/workflows/pulumi.yml@master
    with:
      pulumiPath: .
      preview: ${{ github.event_name == 'pull_request' }}
    secrets:
      CI_NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
